# Soda configuration for dbt integration
# This will ingest dbt test results into Soda Cloud (if configured)
data_source global_macro_dbt:
  type: dbt
  dbt_project_dir: ../dbt
  dbt_profiles_dir: ../dbt
  dbt_target: default
